export type SchemeCategory =
  | "maternity"
  | "delivery"
  | "child"
  | "nutrition"
  | "insurance"
  | "savings"
  | "safety";

export type Scheme = {
  icon: string;
  name: string;
  fullName: string;
  ministry: string;
  cat: SchemeCategory;
  amount: string;
  amtClass: "" | "free" | "insurance";
  amtNote: string;
  summary: string;
  eligibility: string[];
  entitlements: string[];
  docs?: string[];
  apply: string;
  helpline?: string;
  portal?: string;
};

export const SCHEMES: Record<string, Scheme> = {
  pmmvy: {
    icon: "🤰",
    name: "PMMVY",
    fullName: "Pradhan Mantri Matru Vandana Yojana",
    ministry: "WCD",
    cat: "maternity",
    amount: "₹5,000",
    amtClass: "",
    amtNote: "+ ₹6,000 if 2nd child is a girl · DBT to mother",
    summary: "Cash incentive for pregnant women & lactating mothers (1st living child)",
    eligibility: [
      "Pregnant woman age 19+",
      "For 1st living child (full ₹5,000) or 2nd if girl (₹6,000)",
      "Not in regular Govt / PSU / Maternity Benefit Act employment",
      "Pregnancy registration within 730 days of LMP",
    ],
    entitlements: [
      "₹3,000 on early registration of pregnancy + first ANC",
      "₹2,000 after delivery registration + first immunization (BCG/OPV/DPT/HepB)",
      "₹6,000 single instalment for 2nd girl child (post-birth)",
    ],
    docs: ["Aadhaar (mother + husband)", "Bank or Post Office passbook", "MCP card", "LMP / USG report"],
    apply: "Anganwadi worker (AWW) · or pmmvy.wcd.gov.in citizen portal · or PMMVY mobile app",
    helpline: "14408",
    portal: "pmmvy.wcd.gov.in",
  },
  jsy: {
    icon: "🏥",
    name: "JSY",
    fullName: "Janani Suraksha Yojana",
    ministry: "NHM · Health",
    cat: "delivery",
    amount: "₹1,400",
    amtClass: "",
    amtNote: "Rural Low-Performing State (UP, Bihar, MP, JH etc) · ₹1,000 urban · ₹500 home",
    summary: "Cash assistance for institutional delivery to reduce out-of-pocket costs",
    eligibility: [
      "Pregnant woman delivering at Govt or accredited private health facility",
      "In Low Performing States (UP, Uttarakhand, Bihar, Jharkhand, MP, Chhattisgarh, Assam, Rajasthan, Odisha, J&K): all ages, any birth order",
      "BPL / SC-ST certificate required only for accredited private institutions",
      "High Performing States: BPL required",
    ],
    entitlements: [
      "₹1,400 cash to mother (rural LPS like UP)",
      "₹1,000 to mother (urban LPS)",
      "₹600 to ASHA in rural areas (₹300 ANC + ₹300 delivery)",
      "₹400 to ASHA in urban areas",
      "Paid within 7 days of delivery to Aadhaar-linked bank account",
    ],
    docs: ["JSY card + MCP card", "Aadhaar", "Bank or Jan Dhan account", "BPL / SC-ST cert (private accredited only)"],
    apply: "ASHA worker registers at first ANC · cash disbursed at PHC after delivery",
    helpline: "104",
  },
  jssk: {
    icon: "💊",
    name: "JSSK",
    fullName: "Janani Shishu Suraksha Karyakram",
    ministry: "NHM · Health",
    cat: "delivery",
    amount: "FREE",
    amtClass: "free",
    amtNote: "Zero out-of-pocket · all costs absorbed by Govt",
    summary: "Completely free delivery and sick newborn / infant care in all Govt health facilities",
    eligibility: [
      "Every pregnant woman delivering at a public health institution (no BPL test, no caste test)",
      "Every sick newborn (0-30 days, extended to 1 year)",
      "Antenatal & postnatal complications also covered",
    ],
    entitlements: [
      "Free delivery — normal AND C-section",
      "Free drugs and consumables",
      "Free diagnostics (lab, USG, blood tests)",
      "Free diet (3 days for normal delivery, 7 days for C-section)",
      "Free blood",
      "Free transport: home → facility → referral → home",
      "No user charges of any kind",
      "Sick newborn: free treatment incl. SNCU stay",
    ],
    apply: "Walk in to any Govt PHC / CHC / DH / medical college · cite \"JSSK\"",
    helpline: "104",
  },
  pmsma: {
    icon: "📅",
    name: "PMSMA",
    fullName: "Pradhan Mantri Surakshit Matritva Abhiyan",
    ministry: "Health · MoHFW",
    cat: "maternity",
    amount: "FREE",
    amtClass: "free",
    amtNote: "9th of every month at Govt facility (next working day if holiday)",
    summary: "Free OBGY specialist ANC on the 9th of every month — identifies high-risk pregnancies",
    eligibility: [
      "All pregnant women in 2nd or 3rd trimester",
      "No income, caste or location restrictions — universal",
      "Special focus on unregistered, dropouts, and high-risk pregnancies",
    ],
    entitlements: [
      "Free consultation by OBGY specialist / radiologist / physician",
      "Free ultrasound (one)",
      "Free lab tests (Hb, urine, sugar, BP, HIV, syphilis, HepB)",
      "Free IFA + Calcium tablets",
      "High-risk pregnancy identification and tracking",
      "Extended PMSMA (since Jan 2022): up to 4 ANCs/month in underserved areas, incentives for 3 extra ANCs",
    ],
    apply: "Walk in to any Govt PHC / CHC / DH on the 9th of any month",
    helpline: "1800-180-1104",
    portal: "pmsma.mohfw.gov.in",
  },
  suman: {
    icon: "🌸",
    name: "SUMAN",
    fullName: "Surakshit Matritva Aashwasan",
    ministry: "Health · MoHFW",
    cat: "maternity",
    amount: "FREE",
    amtClass: "free",
    amtNote: "14 assured services · zero tolerance for denial",
    summary:
      "Zero-expense, dignified, respectful maternal care for pregnant women + postpartum mothers up to 6 months",
    eligibility: [
      "All pregnant women",
      "Mothers up to 6 months postpartum",
      "All sick newborns",
      "Universal — no income / caste / age filter",
    ],
    entitlements: [
      "At least 4 ANC check-ups including one in 1st trimester",
      "One PMSMA check-up",
      "IFA + Calcium supplementation throughout pregnancy",
      "Td (tetanus + diphtheria) vaccine",
      "Free institutional delivery + free C-section if needed",
      "6 home-based newborn care visits by ASHA",
      "Free transport home ↔ facility ↔ referral",
      "Respectful, private, dignified care — no verbal/physical abuse",
      "Informed consent, choice of birth companion",
      "Free family planning post-delivery",
    ],
    apply: "Any SUMAN-notified Govt facility · grievance portal at suman.mohfw.gov.in",
    helpline: "104",
    portal: "suman.mohfw.gov.in",
  },
  pmjay: {
    icon: "🛡️",
    name: "Ayushman Bharat",
    fullName: "Pradhan Mantri Jan Arogya Yojana (AB-PMJAY)",
    ministry: "Health · NHA",
    cat: "insurance",
    amount: "₹5,00,000",
    amtClass: "insurance",
    amtNote: "per family per year · cashless · pre-existing covered Day 1",
    summary:
      "India's flagship health insurance — covers secondary + tertiary hospitalization for ~55 crore people",
    eligibility: [
      "SECC 2011 deprivation criteria (rural) — kutcha house, no adult, female-headed, manual scavenger, landless etc.",
      "SECC 2011 occupational categories (urban) — domestic worker, rag picker, construction labourer, street vendor etc.",
      "No restriction on family size, age or gender",
      "Senior citizens 70+: covered regardless of income (since Sep 2024) with separate Vay Vandana card",
    ],
    entitlements: [
      "Cashless treatment at 30,000+ empanelled hospitals (public + private)",
      "27 specialities covered: cardiology, oncology, neuro, paeds, ortho, nephrology, urology etc.",
      "1,949 medical packages incl. surgery, diagnostics, drugs",
      "3 days pre-hospitalization + 15 days post-hospitalization expenses",
      "Pre-existing conditions covered from Day 1",
      "Mobile across India — usable in any state",
    ],
    docs: ["Aadhaar", "Ration card", "Family ID (if issued)"],
    apply: "pmjay.gov.in · \"Am I Eligible\" check · Common Service Centre (CSC) · Ayushman Mitra at hospital",
    helpline: "14555 / 1800-111-565",
    portal: "pmjay.gov.in",
  },
  poshan: {
    icon: "🥬",
    name: "POSHAN 2.0",
    fullName: "Mission Saksham Anganwadi & POSHAN 2.0",
    ministry: "WCD",
    cat: "nutrition",
    amount: "FREE",
    amtClass: "free",
    amtNote: "THR · 600 kcal + 18-20g protein/day · 300 days/year",
    summary:
      "Take-Home Ration + Hot Cooked Meals + ECCE via Anganwadi network (1.4 cr+ AWCs nationwide)",
    eligibility: [
      "Pregnant women",
      "Lactating mothers",
      "Children 6 months – 6 years",
      "Adolescent girls 14-18 years (in Aspirational Districts + North-Eastern States)",
      "Universal — no BPL test",
    ],
    entitlements: [
      "Take-Home Ration (THR): 600 kcal + 18-20g protein + micronutrients per day, 300 days/year",
      "Hot Cooked Meal at Anganwadi for 3-6 year children",
      "Pre-school education (ECCE) for 3-6 year children",
      "Free IFA + Calcium supplementation",
      "Growth monitoring (digital — Poshan Tracker)",
      "Nutrition & Health Education (NHED) sessions",
      "Immunization referral via UIP",
      "Health check-ups via RBSK",
      "Referral services to PHC/CHC",
      "Facial Recognition System (FRS) for THR verification (since 1 July 2025)",
    ],
    apply: "Walk in to your local Anganwadi Centre · register with Anganwadi Worker (AWW)",
    helpline: "14408 (multilingual)",
  },
  rbsk: {
    icon: "👶",
    name: "RBSK",
    fullName: "Rashtriya Bal Swasthya Karyakram",
    ministry: "NHM · Health",
    cat: "child",
    amount: "FREE",
    amtClass: "free",
    amtNote: "Including tertiary surgery (cleft lip, heart, club foot etc.)",
    summary:
      "Free screening of 0-18 year children for 4Ds — Defects, Diseases, Deficiencies, Developmental delays (30+ conditions)",
    eligibility: [
      "All children 0-18 years",
      "Auto-enrolled via Anganwadi (0-6) or Govt/aided school (6-18)",
      "Universal — no income test",
    ],
    entitlements: [
      "Newborn screening at delivery point (Medical Officer / Staff Nurse)",
      "Home screening by ASHA (48 hrs to 6 weeks)",
      "Anganwadi screening by 4-member Mobile Health Team (6 weeks – 6 years)",
      "School screening (6-18 years) twice a year",
      "Free referral to District Early Intervention Centre (DEIC)",
      "Free surgery + follow-up at tertiary hospital",
      "30+ conditions screened: birth defects (cleft, club foot, congenital heart, neural tube), deficiencies (anaemia, vit A/D, iodine), diseases (skin, dental, otitis, vision/hearing, congenital cataract, RHD), developmental delays (autism, cerebral palsy, learning disability)",
    ],
    apply: "Automatic via Anganwadi / school · or ASHA referral · or walk-in to DEIC",
    helpline: "104",
  },
  uip: {
    icon: "💉",
    name: "UIP / Indradhanush",
    fullName: "Universal Immunization Programme + Intensified Mission Indradhanush",
    ministry: "NHM · Health",
    cat: "child",
    amount: "FREE",
    amtClass: "free",
    amtNote: "All vaccines · all sessions · for life",
    summary:
      "Free vaccines for children 0-5 years + pregnant women — protects against 12 vaccine-preventable diseases",
    eligibility: [
      "All children 0-5 years",
      "All pregnant women",
      "Universal — no income test",
      "Special focus on left-out / drop-out children via Intensified Mission Indradhanush (IMI 5.0+)",
    ],
    entitlements: [
      "BCG (TB) at birth",
      "Hepatitis B birth dose + 3 doses with Pentavalent",
      "OPV (polio) — 4 doses + IPV — 2 doses",
      "Pentavalent (DPT + Hep B + Hib) — 3 doses (6, 10, 14 weeks)",
      "Rotavirus (diarrhoea) — 3 doses",
      "PCV (Pneumococcal Conjugate) — 3 doses",
      "MR (Measles + Rubella) — 2 doses (9 mo, 16-24 mo)",
      "JE (Japanese Encephalitis) — endemic districts",
      "DPT booster (16-24 mo, 5-6 yrs)",
      "Td booster — adolescents at 10 & 16 yrs",
      "Td (replaces TT) — 2 doses for pregnant women + 1 booster",
      "U-WIN digital platform for tracking + reminders",
    ],
    apply: "Anganwadi / PHC / Sub-centre / Govt hospital on fixed Immunization Days · IMI rounds for left-out kids",
    helpline: "1800-180-1101",
    portal: "U-WIN (uwin.mohfw.gov.in)",
  },
  ssy: {
    icon: "👧",
    name: "Sukanya Samriddhi",
    fullName: "Sukanya Samriddhi Yojana (under BBBP)",
    ministry: "Finance + WCD",
    cat: "savings",
    amount: "8.2% p.a.",
    amtClass: "",
    amtNote: "Tax-free interest · Section 80C deductible · for girl child",
    summary: "Govt-backed savings account for girl child under 10 — for higher education & marriage",
    eligibility: [
      "Girl child below age 10",
      "Indian resident",
      "Maximum 2 accounts per family (one per girl child)",
      "NRIs and HUFs not eligible",
    ],
    entitlements: [
      "8.2% p.a. interest (compounded yearly, EEE tax status)",
      "Min ₹250/year · Max ₹1.5 lakh/year (Section 80C eligible)",
      "Deposits for 15 years from account opening",
      "Account matures at 21 years from opening",
      "50% partial withdrawal allowed at age 18 (for education)",
      "Premature closure allowed for marriage (after age 18)",
      "Transferable between Post Offices / banks",
    ],
    docs: ["Birth certificate of girl child", "Aadhaar of parent/guardian", "Address proof", "Photo"],
    apply: "Any India Post Office or authorized bank (SBI, PNB, BoB, Canara, ICICI, HDFC, Axis etc.)",
    helpline: "1800-266-6868 (India Post)",
  },
  bbbp: {
    icon: "🌷",
    name: "BBBP",
    fullName: "Beti Bachao Beti Padhao",
    ministry: "WCD + Health + Education",
    cat: "safety",
    amount: "Awareness +",
    amtClass: "",
    amtNote: "Linked to SSY, scholarships, KGBV school",
    summary:
      "National campaign to improve child sex ratio + ensure girl child survival, protection & education",
    eligibility: [
      "Universal — all families with girl children under 10",
      "Special intensive intervention in 100+ gender-critical districts",
      "Sub-component of Mission Shakti SAMBAL",
    ],
    entitlements: [
      "Free school enrolment & retention support for girls",
      "Linkage to Sukanya Samriddhi Yojana (savings)",
      "Linkage to Kasturba Gandhi Balika Vidyalaya (KGBV) — residential school for adolescent girls",
      "Self-defence training in schools",
      "Menstrual hygiene programmes",
      "Anti-PCPNDT Act enforcement (banning sex-selective abortion)",
      "Selfie-with-Daughter campaign and awareness drives",
    ],
    apply: "Through Anganwadi · Education department · ASHA",
    portal: "wcd.gov.in/bbbp-scheme",
  },
  shakti181: {
    icon: "📞",
    name: "Helpline 181",
    fullName: "Women Helpline (WHL) · Mission Shakti SAMBAL",
    ministry: "WCD",
    cat: "safety",
    amount: "FREE",
    amtClass: "free",
    amtNote: "24×7×365 toll-free · all languages",
    summary:
      "Emergency response for women in distress — DV, harassment, trafficking · integrates 112 + 1098",
    eligibility: [
      "Any woman or girl in distress, any age",
      "Any state, any time",
      "Public or private space",
      "Universal — no documents needed to call",
    ],
    entitlements: [
      "24×7 free emergency phone response",
      "Police assistance (linked to 112 ERSS)",
      "Medical aid coordination",
      "Legal aid & counselling",
      "Referral to One Stop Centre (Sakhi)",
      "Information on women welfare schemes",
      "Integrated with Child Helpline 1098",
    ],
    apply: "Just dial 181 from any phone — landline or mobile",
    helpline: "181",
  },
  osc: {
    icon: "🏠",
    name: "Sakhi · One Stop Centre",
    fullName: "One Stop Centre (OSC) · Mission Shakti SAMBAL",
    ministry: "WCD",
    cat: "safety",
    amount: "FREE",
    amtClass: "free",
    amtNote: "Integrated services under one roof",
    summary:
      "Integrated medical + legal + police + shelter + counselling for women affected by violence",
    eligibility: [
      "Women affected by any form of violence — physical, sexual, emotional, psychological, economic",
      "All ages, castes, classes, marital statuses, religions",
      "Walk-in or referred via 181 / 112",
    ],
    entitlements: [
      "Emergency response under one roof",
      "Police assistance",
      "Medical first aid + linkage to hospital",
      "Legal aid + advice (linked to DLSA)",
      "Psycho-social counselling",
      "Temporary shelter up to 5 days",
      "Linkage to Shakti Sadan (long-term shelter for trafficked/DV victims)",
      "For girls <18: linked with Juvenile Justice Act + POCSO institutions",
    ],
    apply: "Walk in to nearest Sakhi OSC (one per district) · or call 181 / 112",
    helpline: "181",
  },
};

export const SCHEME_CATEGORIES: Array<{ id: SchemeCategory | "all"; label: string; icon: string }> = [
  { id: "all", label: "All", icon: "📋" },
  { id: "maternity", label: "Pregnancy", icon: "🤰" },
  { id: "delivery", label: "Delivery", icon: "🏥" },
  { id: "child", label: "Children", icon: "👶" },
  { id: "nutrition", label: "Nutrition", icon: "🥬" },
  { id: "insurance", label: "Insurance", icon: "🛡️" },
  { id: "savings", label: "Savings", icon: "💰" },
  { id: "safety", label: "Safety", icon: "🚨" },
];
